name: Deploy to Azure Web App

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    - uses: actions/checkout@v3

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci

    - name: Run build script
      run: npm run build

    - name: List deployment contents
      run: |
        Write-Host ""
        Write-Host "Build directory contents:" -ForegroundColor Blue
        Get-ChildItem ./dist

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: app
        path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ vars.AZURE_WEBAPP_NAME }}
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
